name = "hassio-proxy-worker"
main = "dist/index.js"
compatibility_date = "2025-08-01"

[ai]
binding = "AI"

# Placeholders so we don’t touch this again next PR
[[d1_databases]]
binding = "D1_DB"
database_name = "hassio_proxy_db"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "hassio-proxy-artifacts"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "HomeAssistantWebSocket"
