name = "hassio-proxy"
main = "src/index.ts"
compatibility_date = "2025-08-01"

[ai]
binding = "AI"

[observability]
enabled = true

[[d1_databases]]
binding = "D1_DB"
database_name = "hassio_proxy_db"
database_id = "ba740a1f-2c2f-48cb-aeb6-470fe8dc329d"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "2c6f36343c62419fa8fc0cbd4a0029ac"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "919f3f3ae9fc4a058e038816a8329157"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "cc09952642ca471fbdf8ab28ba3ab512"

[[r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "hassio-proxy-logs"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "HomeAssistantWebSocket"
